- examples/example.c
The example.c file did not compile because it had various errors in it. This patch fixes those.
(Let me know if you want me to stop sending you bug reports and pull requests. I've just been looking through SuperNOVAS which helped me understand a few concepts in NOVAS itself which I previously didn't quite get...)
> Fixed errors in example.c

- Makefile
- build.mk
- config.mk
This way the default 'make' does not require special build dependencies (like doxygen) being present.
Also, `make help` can now be used to show and explain the available build targets.
> Default build 'dox' target conditional on doxygen being present

- .gitignore
- CHANGELOG.md
- Makefile
- README.md
- config.mk
- include/novas.h
- src/cio_file.c
- src/version.c
- #23 -- Various build improvements with easier packaging in mind
- #24 -- Fix ill-defined `SUPERNOVAS_VERSION_STRING`
- Fixes to `cio_file` (normally used only at build time).
> Build improvements (and fixes) to facilitate downstream packaging

- .github/workflows/test.yml
Add regression testing on:
- armv7
- aarch64
- riscv64
- ppc64le
> CI Regression testing on different platforms also

- .settings/language.settings.xml
- codecov.yml
- config.mk
- include/novas.h
- src/novas.c
- test/src/test-errors.c
- test/src/test-super.c
The inverse function for `grav_def()`.
Also:
- Fix up test cases but initializing all data to avoid unreproducible behavior in tests.
- Use precompiler constants to define max number of iterations for inverse methods.
> grav_undef() to gravitationally unbend observed light

- .gitignore
- CHANGELOG.md
- Doxyfile
- LEGACY.md
- Makefile
- README.md
- build.mk
- include/eph_manager.h
- include/novas.h
- include/novascon.h
- include/nutation.h
- include/solarsystem.h
- src/cio_file.c
- src/eph_manager.c
- src/frames.c
- src/novas.c
- src/novascon.c
- src/nutation.c
- src/readeph0.c
- src/refract.c
- src/solsys-ephem.c
- src/solsys1.c
- src/solsys2.c
- src/solsys3.c
- src/timescale.c
- test/Makefile
- test/src/test-errors.c
- test/src/test-super.c
- Added `novas_planet_bundle` to handle planet data (e.g. for gravitational deflection) more elegantly.
- Added `cirs_to_tod()` and `tod_to_cirs()`
- `novas_geom_posvel()` to use frame-internal planet data if possible.
- `frame_aberration` to calculate inverse iteratively
- Remove `accuracy` argument from new `grav_undo_planets()` to simplify. 
- Refactor `novas_tcb_diff()` / `novas_tcg_diff()` to `novas_diff_tcb()` / `novas_diff_tcg()`.
- A few error traces that were missed before
- doxygen edits
- Updates to `README.md` and `CHANGELOG.md`
- Makefile edits and tweaks 
- Test for convergence failures
> v1.1.0 release composition

- .settings/language.settings.xml
- README.md
- include/novas.h
- src/novas.c
- test/src/test-errors.c
- test/src/test-super.c
So far, sidereal (i.e. catalog) sources were defined with parameters typical for stars in our Galaxy. As such, motion was parametrized by radial velocity (in line of sight) , as well as proper motion. And, as a result, NOVAS did not offer proper support for handling distant quasars or galaxies, where line-of-sight motion is more typically parameterized with a redshift (z) instead.
Thus we now add:
- `novas_z2v()` to convert redshift values (z) to an equivalent radial velocity (in km/s).
- `novas_v2z()` to convert radial velocity values(in km/s) to an equivalent redshift (z).
- `make_redshifted_object()` to simplify the initialization of distant sources parameterized by redshift. It will set proper motion and parallax to zero, and initialized the source catalog to `EXT` to indicate an …
> Redshifted motion handling

- .settings/language.settings.xml
- config.mk
- src/novas.c
- src/super.c
- test/Makefile
Add new `super.c` with SuperNOVAS only functions that are not required by `novas.c`. With it we reduce the bloating of the already  large `novas.c` source a little. At the same time we continue to support linking against `novas.o` for legacy NOVAS C applications, which might want it.
> Separate super.c source module.

- Makefile
- build.mk
- config.mk
- test/Makefile
- Added variables for output directories `OBJ` for objects, `LIB` for libraries, and `BIN` for binaries. You can change where the compiled files go, either by editing `config.mk` or by setting the above variables in the shell prior to invoking `make`
- Added `CHECKEXTRA` variable that can define additional options to pass to `cppcheck`, e.g. by defining it in the shell prior to invoking `make`
- Some reorganization among the make files, and some tweaks
> make: Added configurability, better organized etc.

- include/novas.h
- src/novas.c
- src/refract.c
- src/super.c
- test/src/test-errors.c
Enhance debug mode to properly report when NAN values are returned by a function in case of an error. (Previously the traces showed a 'fictional' integer value for these).
> Separate error tracing for NAN returns

- src/novas.c
- src/readeph0.c
- src/refract.c
- src/super.c
- src/timescale.c
- test/src/test-errors.c
Incomplete error traces in:
- `tod_to_cirs()`
- `cirs_to_tod()`
- `novas_set_time()`
- `novas_get_time()`
- `novas_diff_tcb()`
- `novas_diff_tcg()`
- `novas_set_unix_time()`
- `novas_get_unix_time()`
- `novas_refraction()`
superfluous error checking (propagate instead) in:
- `j2000_to_tod()`
- `tod_to_j2000()`
Unnecessary error variable in:
- `transform_cat()`
Wrong error trace name for
- `novas_get_split_time()`
Non-existing function called in 
- `readeph_dummy()`
> Debug error tracing fixes and tweaks

- README.md
The "Calculating Positions for a Sidereal Source" section of the README had a few typos
> Fix a handful of README typos

- build.mk
- include/novas.h
- src/frames.c
- src/novas.c
- src/refract.c
- src/super.c
Mode code style fixes:
- initializer macros (exposed with `-Wextra`)
- 'Using' unused variables after declarations (old style).
- Makefile without order-only dependencies (for older `make`).
> Initializer macros, and old-style declarations.

- CHANGELOG.md
- Doxyfile
- README.md
- include/novas.h
- src/novas.c
- src/super.c
- test/Makefile
- test/src/test-errors.c
- test/src/test-super.c
- #57: New `novas_make_redshifted_object()` to simplify the creation of distant catalog sources that are characterized with a redshift measure rather than a radial velocity value.
- #57: New generic redshift-handling functions `novas_v2z()`, `novas_z2v()`, 
- #58: New functions to calculate and apply additional gravitational redshift corrections for light that originates near massive gravitating bodies (other than major planets, or Sun or Moon), or for observers located near massive gravitating bodies (other than the Sun and Earth). The added functions are `grav_redshift()`, `redhift_vrad()`, `unredshift_vrad()`, `novas_z_add()`, and `novas_z_inv()`.
> Redshift utilities

- CHANGELOG.md
- Makefile
- README.md
- config.mk
- include/solarsystem.h
- src/solsys-calceph.c
- src/solsys-cspice.c
- test/Makefile
- test/src/test-calceph.c
- test/src/test-cspice.c
Provides optional ephemeris support via the [NAIF CSPICE Toolkit](https://naif.jpl.nasa.gov/naif/toolkit.html) in separate `solsys-cspice.so[.1]` / `.a` plugin libraries. 
To enable, `CSPICE_SUPPORT` must be set to 1 prior to the build (in the shell or in `config.mk`) and you must have access to the CSPICE development files (C headers and unversioned libaries). You might want to check out the [Smithsonian/cspice-sharedlib](https://github.com/Smithsonian/cspice-sharedlib) repository to help you build CSPICE as a shared library (`libcspice.so[.1]`).
Added functions are:
- `int novas_use_cspice()` -- to use CSPICE for all Solar-system types.
- `int novas_use_cspice_planets()` -- to use CSPICE for major planets (and Sun, Moon, SSB) only.
- `int novas_use_cspice_ephem()` -- to use CSPICE for …
> CSPICE integration

- CHANGELOG.md
- README.md
- include/solarsystem.h
- src/solsys-calceph.c
- src/solsys-cspice.c
- test/src/test-cspice.c
- Improved error handling, printing CSPICE short error messages when debug mode is enabled.
- Added convenience functions to manage active kernels:
* `novas_cspice_add_kernel()`  -- wraps the CSPICE `furnsh_c()` with graceful error handling.
* `novas_cspice_remove_kernel()`  -- wraps the CSPICE `unload_c()` with graceful error handling.
> Further CSPICE support, improved error handling

- .github/workflows/build.yml
- .github/workflows/dox.yml
- .github/workflows/install.yml
- .github/workflows/test.yml
- CHANGELOG.md
- Makefile
- README.md
Adds a `install` target to the `Makefile`, using the [standard directory variables](https://www.gnu.org/prep/standards/html_node/Directory-Variables.html), with the recommended default values. As such it can take a `prefix` argument, e.g.:
```bash
sudo make prefix=/opt install
``` 
To install under `/opt` rather than the default `/usr` prefix.
> Add install target

- CHANGELOG.md
- README.md
- include/novas.h
- include/solarsystem.h
- src/naif.c
- src/novas.c
- src/solsys-calceph.c
- src/solsys-cspice.c
- src/solsys-ephem.c
- src/solsys1.c
- src/solsys2.c
- test/src/test-errors.c
- test/src/test-super.c
For most planetary systems, there isn't much of a difference between the position of the planet center and the planetary system barycenter, since either the planet has no significant satellites, or else they are tiny compared to the planet itself.
The Earth-Moon system, and the Pluto system are the exceptions to the rule. In these systems the satellites have more comparable mass to the planet, and hence the planet center is significantly offset from the system's barycenter.
Until now, NOVAS did not distinguish between Earth vs Earth-Moon Barycenter (EMB) or Pluto (planet) vs Pluto system. But planetary ephemeris providers, such as the DExxx ephemeris data from JPL do make that distrinction. Hence expand `enum novas_planet` to include the Earth-Moon Barycenter (`NOVAS_EMB`) and the Pluto …
> EMB and Pluto Barycenter

- CHANGELOG.md
- README.md
- include/novas.h
- include/solarsystem.h
- src/frames.c
- src/novas.c
- src/super.c
- test/src/test-errors.c
- test/src/test-super.c
- `NOVAS_ORBITAL_OBJECT` to `enum novas_planet`.
- `novas_orbital_elements` structure, including `novas_orbital_system` substructure, and `enum novas_reference_plane` to distiguish ecliptic vs equatorial orbital parameters, and `novas_set_orbital_pole()` helper function to configure.
- `object.orbit` field containing `novas_orbital_elements` data
- `novas_orbit_posvel()` function to calculate position and velocity vectors from orbital elements.
- `make_orbital_object()` function to ease the creation of objects with orbital parameters.
- `ephemeris()` call to process `NOVAS_ORBITAL_OBJECT` types via `novas_orbit_posvel()`.
> Orbital elements based calculations

- CHANGELOG.md
- README.md
- include/novas.h
- src/novas.c
- src/super.c
- test/src/test-errors.c
- test/src/test-super.c
- Tweak `enum novas_orbital_system` to o contain a proper reference coordinate system instead of just an equator type.
- Renamed `novas_set_orbital_pole()` to `novas_set_orbsys_pole()`, which now takes a coordinate reference system as an input, in line with the above.
- Exposed existing `gcrs_to_tod()` and `tod_to_gcrs()` functions.
- Added `gcrs_to_mod()` and `mod_to_gcrs()` functions for convenience.
> Orbitals continued

- CHANGELOG.md
- include/novas.h
- src/novas.c
- src/super.c
To complement `make_redshifted_object()` added earlier. A `cat_entry` is a  much smaller footprint container, and which can be warpped into an `object` when needed.
> Add make_redshifted_cat_entry() function

- .github/workflows/dox.yml
Reverts Smithsonian/SuperNOVAS#119
It has the doxygen  bug for anchors.
> Revert "Bump mattnotmitt/doxygen-action from 1.9.8 to 1.12.0"

- CHANGELOG.md
- README.md
- include/novas.h
- src/novas.c
- src/timescale.c
- test/src/test-super.c
Affects:
- `julian_date()`
- `cal_date()`
- `novas_parse_date_format()` / `novas_parse_date()`
- `novas_timestamp()` / `novas_iso_timestamp()`
Adds:
- `cal_date2()`, which works like `cal_date()` but takes `int *` pointers intead of `short *`.
> Negative years to indicate B.C. dates consistently

- CHANGELOG.md
- README.md
- include/novas.h
- src/novas.c
- src/super.c
- src/timescale.c
- test/src/test-errors.c
- test/src/test-super.c
- Replace `cal_date2()` from #121 with `novas_jd_to_calendar()` which converts to dates in the specified type of calendar.
- Add `novas_calendar_to_jd()` to convert dates in specific calendars to JD days.
> Disambiguate Gregorian and Roman/Julian calendars.

- .github/workflows/test.yml
The `run-on-arch-action` workflow has been broken for ppc64le and s390x platforms for a while, with `cc` failing with a Segmentation fault on `ubuntu-latest`. It seems like a compiler bug for the version of `gcc` that is currently on `ubuntu_latest`. Once it is fixed, and the compilation is successful, we can re-merge to `main`.
> Reinstate CI testing on s390x and ppc64le platforms

- CHANGELOG.md
- Makefile
- examples/example-time.c
- include/novas.h
- src/super.c
- src/timescale.c
- test/src/test-errors.c
- test/src/test-super.c
- `double novas_date(const char *restrict date);`
- `double novas_date_scale(const char *restrict date, enum novas_timescale *restrict scale);`
- Add parsing tailing compass directions (N, E, S, W) to `novas_parse_dms()` and `novas_dms_degrees()`.
> Further date parsing functions

- CHANGELOG.md
- README.md
- examples/example-time.c
- src/super.c
- test/src/test-super.c
Be able to parse, e.g.:
```
-179°59’59.999”
```
> degree, minutes, and seconds as extended ASCII symbols

- CHANGELOG.md
- include/novas.h
- src/timescale.c
- test/src/test-errors.c
- test/src/test-super.c
Like `novas_timescale_for_string()` but ignores leading white spaces and also returns an updated parse position.
> Add novas_parse_timescale()

- CHANGELOG.md
- README.md
- examples/example-high-z.c
- examples/example-star.c
- include/novas.h
- src/parse.c
- src/timescale.c
- test/src/test-errors.c
- test/src/test-super.c
- Add `novas_str_degrees()` and `novas_str_hours()`
- `novas_dms_degrees()` / `novas_hms_hours()` to set `errno` to `EINVAL` if there are unparsed tokens.
- Allow ommitting the seconds component in HMS/DMS specifications.
- Some doxygen apidoc corrections.
- Allow 2-componend h+m or d+m parsing
- Allow punctuation after compass direction
> Add `novas_str_degrees()` and `novas_str_hours()`

- src/parse.c
- src/super.c
- src/timescale.c
- test/src/test-super.c
- recognize `d`, `dg`, `deg`, `degree`, and `degrees` (case insensitive) as degree units.
- recognize `h`, `hr`, `hrs`, `hour`, and `hours` (case insensitive) as hour units.
- Fixes to returned tail pointer when parsing hours/degrees
- `novas_parse_date()` / `novas_parse_date_format()` not to consume empty spaces after date specification.
> Improved hours/degrees unit parsing

- src/frames.c
- Bad bracket placement in rise/set/transit time calculation caused times to be systematically off by minutes.
- Also fix refraction unit.
> Fixes to rise/set/transit time calculations

- src/parse.c
- test/src/test-super.c
Further improvements to string angle parsing.
- Allow full word compass directions (case insensitive) also -- e.g. 'North', or 'WEST', or 'east'.
- Support for both leading and trailing compass directions (but not both).
> Improved compass direction parsing

- CHANGELOG.md
- src/equinox.c
In case someone calls it repeatedly with the same input parameters, now it will be much much faster...
> Add caching to `ee_ct()`

- CHANGELOG.md
- include/novas.h
- src/parse.c
- test/src/test-errors.c
Improved checking for invalid decimal seconds when parsing DSM angle strings.
> `parse_degrees()` check invalid seconds

- CHANGELOG.md
- src/util.c
- test/src/test-super.c
- `novas_sep()` to check `sqrt()` argument, in case of rounding errors push it negative.
- testing of `ira_equinox()` with tolerance for rounding errors.
> Fixes for Debian i386 cross builds

- CHANGELOG.md
- src/parse.c
- test/src/test-super.c
- Add support for parsing degrees in exponential notation, e.g. `1.23E2` or `1.23E-2W` etc. (Previously this was not possible due to the the duality of `E` being used as a compass direction also.)
> Parsing degrees in exponential notation

- CHANGELOG.md
- README.md
- include/novas.h
- src/frames.c
- src/refract.c
- test/src/test-errors.c
- test/src/test-super.c
- Add `novas_wave_refraction()`, which provides as `RefractionModel` implementation for SuperNOVAS that is based on the IAU/SOFA `iauRefco()` function.
- Add `novas_refract_wavelength()` to allow specifying the observing wavelength for which refraction is to be calculated for when using wavelength-dependent refraction models, such as the above. 
- Added range checking to `refract()` function and `novas_radio_refraction()` model.
> Add IAU/SOFA refraction model implementation

- CHANGELOG.md
- src/earth.c
- src/frames.c
- Missing wobble corrections in frame-based approach (PEF <--> ITRS).
- Old-style (now disfavored) wobble corrections via `cel_pole()` were not applied to true obliquity and the equation of the equinoxes in `e_tilt()`.
- Deprecate `cel_pole()` function and the `PSI_COR` / `EPS_COR` variables, which supported the old-style (now disfavored) way of dealing with Earth orientations parameters.
> Fixes to Earth orientation (polar wobble) corrections

- CHANGELOG.md
- README.md
- include/novas.h
- src/refract.c
- test/src/test-errors.c
- test/src/test-super.c
Added:
- `NOVAS_RADIO_REFRACTION` to use the Berman & Rockwell 1972 radio refraction model.
- `NOVAS_WAVE_REFRACTION` to use the IAU / SOFA wavelength-dependent refraction model. (The wavelength can be set via `novas_refract_wavelength()`)
Also, tweaks to error propagation...
> New `enum novas_refraction_model` values.

- .github/workflows/build.yml
- CHANGELOG.md
- Makefile
- build.mk
- config.mk
Fix `Makefile` to work with reverse order (or parallel) builds.
> Fix Makefile deps so reverse order build works also

- CHANGELOG.md
- include/novas.h
- src/earth.c
- src/itrf.c
- test/src/test-errors.c
- test/src/test-super.c
Transformations between geodetic coordinates (longitude, latitude, altitude) and geocentric Cartesian coordinates (x, y, z) to allow chosing what reference ellipsoid to use. Currenly, one may chose between the GRS80 ellipsoid (`NOVAS_GRS80`), which is generally adopted by the IERS conventions, or else the WGS84 ellipsoid (`NOVAS_WGS84`).
> cartesian-geodetic conversion to use specified reference ellipsoid

- .github/workflows/build-cmake.yml
- .gitignore
- CMakeLists.txt
- Doxyfile
- README_CMAKE.md
- cmake/SuperNOVASConfig.cmake.in
- cmake/cmake_uninstall.cmake.in
- cmake/supernovas.pc.in
- examples/CMakeLists.txt
Ok, as an alternative to PR #221, here is a CMake version of the build.
It is trimmed-down compared to the Makefile build, but is pretty useful as it allows easy inclusion in other CMake projects, generates a pkgconfig file, and builds on everything (inlcuding windows!). It does not, however, build the tests/benchmarks/or docs.
If we go with this, we can leave your makefile untouched.
> Add CMake build tooling

- CHANGELOG.md
- CMakeLists.txt
- Makefile
- examples/CMakeLists.txt
- src/docedit.c
- test/CMakeLists.txt
- test/src/test-calceph.c
- test/src/test-cio_file.c
- test/src/test-compat.c
- test/src/test-cspice.c
- test/src/test-errors.c
- test/src/test-super.c
- Build without `sed`, `bash`, or `tail`...
- Source with platform-dependent path separator (`\` on Windows vs '/' on everything else). 
Also:
- select install of include files, depending on build options (not whole directory)
> Non-UNIX builds / functionality

- CHANGELOG.md
- include/novas.h
- src/timescale.c
- test/src/test-errors.c
- test/src/test-super.c
One `novas_clock_skew()` function to rule them all. (It takes a reference timescale argument, hence replacing multiple variants from before.)
> Consolidate `novas_clock_skew()`

- CHANGELOG.md
- include/novas.h
- src/timescale.c
- test/src/test-errors.c
- test/src/test-super.c
Added
```c
double novas_mean_clock_skew(const novas_frame *frame, enum novas_timescale timescale);
```
which discounts tidal variations for Earth-bound observers as they rotate around the geocenter.
> Mean vs instantaneous clock skews

- CHANGELOG.md
- CMakeLists.txt
- Makefile
- README.md
- include/novas.h
- src/cio.c
- test/src/test-super.c
And, also no default CIO data location set unless in `COMPAT` mode (in which case the NOVAS C `./cio_array.bin` is used.
Follows #208.
> Don't install CIO locator data

- CHANGELOG.md
- CMakeLists.txt
- Doxyfile
- Makefile
Both CMake and GNU make to install the following in `$(docdir)/supernovas/`:
- `README.md`
- `LEGACY.md`
- `CHANGELOG.md`
- `CONTRIBUTING.md`
- `examples/`
- `legacy/`
Also compile `resources/supernovas_vs_astropy.md` into HTML.
> Install more documentation

- CHANGELOG.md
- Doxyfile
- LEGACY.md
- Makefile
- README.md
- resources/header.html
- src/docedit.c
Add HTML comments with doxygen command to skip badges and logo, so we no longer need to create a headless `README-orig.md`
> Doxygen to use README.md as is.

- .github/workflows/test.yml
- .settings/language.settings.xml
- CHANGELOG.md
- README.md
- examples/example-rise-set.c
- examples/example-star.c
- include/novas.h
- src/calendar.c
- src/frames.c
- src/parse.c
- src/spectral.c
- src/target.c
- src/timescale.c
- test/src/test-errors.c
- test/src/test-super.c
New functions to define `cat_entry`data step-by-step, and with more flexibility than the NOVAS C `make_cat_entry()`...
1. Initialize the `cat_entry` with source name and RA/Dec coordinates using `novas_init_cat_entry()`.
2. (optional) Set radial velocity, as needed, via either:
(a) radial velocity w.r.t SSB using `novas_set_ssb_vel()`, or
(b) LSR velocity using `novas_set_lsr_vel()`, or
(c) redshift using `novas_set_redshift()`.
3. (optional) Set proper motions (mas/yr), as needed, using `novas_set_proper_motion()`.
4. (optional) Set parallax, as needed, via either:
(a) parallax (mas) using `novas_set_parallax()`, or
(b) distance (parcsec) using `novas_set_distance()`.
5. (optional) Assign catalog info if desired via `novas_set_catalog()`.
> Define catalog sources step-by-step

- CHANGELOG.md
- README.md
- include/novas.h
- include/solarsystem.h
- src/equinox.c
- src/grav.c
- src/observer.c
- src/spectral.c
- src/util.c
You can define `_EXCLUDE_DEPRECATED`, either as a compiler option `-D_EXCLUDE_DEPRECATED`, or else in your source code by defining `_EXCLUDE_DEPRECATED` __before__ including `novas.h`, to exclude deprecated definitions. E.g.,
```c
// Include novas.h without the deprecated API
#define _EXCLUDE_DEPRECATED
#include <novas.h>
```
> Option to exclude deprecated definitions from novas.h

- .github/workflows/build-cmake.yml
- .github/workflows/build.yml
- CHANGELOG.md
- CMakeLists.txt
- Makefile
- README.md
- build.mk
- config.mk
- examples/CMakeLists.txt
- examples/Makefile
- examples/example-cspice.c
- test/Makefile
- Fixes to CALCEPH / CSPICE build with CMake
- Standalone `CMakeLists.txt` for examples.
- Self contained `make help`  for examples.
- Various other tweaks
> Tweak build configs

- .github/workflows/build-cmake.yml
- CHANGELOG.md
- CMakeLists.txt
- README.md
- benchmark/benchmark-nutation.c
- benchmark/benchmark-place.c
- examples/example-time.c
- include/novas.h
- src/frames.c
- src/parse.c
- src/refract.c
- src/target.c
- src/timescale.c
- src/util.c
- test/src/test-errors.c
- test/src/test-super.c
Various changes to enable non-UNIX builds, esp. with MSVC.
- No more `unistd.h` includes. It's a UNIX-specific header, and it turns out we did not need it at all.
- Use the MSVC `_stricmp()` and `_strincmp()` instead of the UNIX `strcasecmp()` and `strncasecmp()`, when compiling with MSC.
- Use the C11 `timespec_get()` instead of the UNIX-specific `clock_gettime()` when appropriate.
- Various fixes to tests of small issues, which did not trip up gcc / clang.
- New 'internal' function `novas_set_max_iter()` to set the global `novas_inv_max_iter` variable (since MSVC does not seem to export the variable).
> Improved portability beyond UNIX (e.g. MSVC)
